license_key=USMNVLCO-1537
machine_fp=d3527df7cc0f7335
signature=Hg4YuVa8YenQBwGAxO3C+HbnrKNuVeKZ8NIeT1tt6KeQLR4lp3fhUcsYqy5ZLeMFnvYIsg2L+zBQMoCwUQpVjYs085f/jXOZw3E4EbSch1Y9vZx5hy2R1/8B/42+TpMmFETw2VLG9YzWKdEENsBmAc9bWSZFrshSbaUtjyC+znJ0V8iu17EGquwI22ClTWEcnpaywIBC6PPLxj1iAtjMZdBpOVATvjH7s2KkuB728O3tVbrCCgPq/ZZv3JF+5ukFZP2qCTbC7IwqMsmBkaxPluECMb6dFyPsbk8G2g/BoRETuFgSQPqALwA5/7WIz8vufD8V0Az8MFlVqQDFpQYhmA==
