#!/usr/bin/env python3
"""
Generate a signed `license.properties` file for LOCAL DEV testing.

This is the dev-mode replacement for the deleted `data.LicenseGenerator`
Java class (which used to ship inside the production JAR — bad). The
output file is identical in shape to what the Inno Setup installer
produces, so the game accepts it transparently.

Reads the RSA private key from `build_tools/license_private_pkcs8.b64`
(generated by `generate_license_keys.py`). Computes the local machine
fingerprint the same way LicenseManager.java does, then RSA-signs
"license_key|machine_fp".

Usage:
    python build_tools/generate_dev_license.py
    python build_tools/generate_dev_license.py --out C:\\path\\license.properties
    python build_tools/generate_dev_license.py --key MICHI001-2DF3
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import os
import secrets
import string
import subprocess
import sys
from pathlib import Path

CHARSET = string.ascii_uppercase + string.digits
SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_PRIV = SCRIPT_DIR / "license_private_pkcs8.b64"
DEFAULT_OUT  = Path("license.properties")


def generate_key() -> str:
    prefix = "".join(secrets.choice(CHARSET) for _ in range(8))
    suffix = "".join(secrets.choice(CHARSET) for _ in range(4))
    return f"{prefix}-{suffix}"


def read_machine_guid() -> str:
    """Mirror LicenseManager.readMachineGuid()."""
    if os.name == "nt":
        try:
            out = subprocess.check_output(
                ["reg", "query",
                 "HKLM\\SOFTWARE\\Microsoft\\Cryptography",
                 "/v", "MachineGuid"],
                stderr=subprocess.DEVNULL,
            ).decode("utf-8", errors="ignore")
            for line in out.splitlines():
                if "REG_SZ" in line:
                    return line.split("REG_SZ", 1)[1].strip()
        except Exception:
            pass
    # Fallback path identical to the Java code.
    return (os.environ.get("COMPUTERNAME") or "unknown") + \
           (os.environ.get("USERNAME") or "user")


def machine_fingerprint() -> str:
    guid = read_machine_guid()
    digest = hashlib.sha256(guid.encode("utf-8")).digest()[:8]
    return digest.hex()


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    p.add_argument("--key", default=None,
                   help="Specific license key to embed (default: random).")
    p.add_argument("--priv", type=Path, default=DEFAULT_PRIV,
                   help="Path to PKCS#8 base64 RSA private key.")
    p.add_argument("--machine-fp", default=None,
                   help="Fixed 16-hex-char fingerprint to embed instead of deriving one from "
                        "this machine's registry (e.g. for baking a license into an Android "
                        "build, which has no Windows MachineGuid to read at runtime).")
    args = p.parse_args()

    if not args.priv.exists():
        print(f"[ERROR] Private key not found: {args.priv}", file=sys.stderr)
        print("        Run: python build_tools/generate_license_keys.py", file=sys.stderr)
        sys.exit(2)

    # Import cryptography lazily so the script can at least print --help
    # without the dependency installed.
    try:
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import padding as rsa_padding
    except ImportError:
        print("[ERROR] pip install cryptography", file=sys.stderr)
        sys.exit(2)

    priv_b64 = args.priv.read_text(encoding="utf-8").strip()
    priv_der = base64.b64decode(priv_b64)
    priv     = serialization.load_der_private_key(priv_der, password=None)

    license_key = args.key or generate_key()
    fp = args.machine_fp or machine_fingerprint()
    msg = f"{license_key}|{fp}".encode("utf-8")
    sig = priv.sign(msg, rsa_padding.PKCS1v15(), hashes.SHA256())
    sig_b64 = base64.b64encode(sig).decode("ascii")

    content = (
        f"license_key={license_key}\r\n"
        f"machine_fp={fp}\r\n"
        f"signature={sig_b64}\r\n"
    )
    args.out.write_text(content, encoding="ascii")

    print(f"[OK] Wrote {args.out}")
    print(f"     license_key = {license_key}")
    print(f"     machine_fp  = {fp}")
    print(f"     signature   = {sig_b64[:48]}...")


if __name__ == "__main__":
    main()
