license_key=9V7KM886-VQW7
machine_fp=d3527df7cc0f7335
signature=IkeUHYqD/tvk2zh/j48ftkAOnBvtaZL9cfOT3v4lo4+/oundd8Y1PDJntGauAzhDsWW1qcHu6heXok6CDEiS2hvPC+Y4JaKsKcmOztvUkqkm+KxYnfnxnbhZMjGYzPV4FP4jh+n0F/RCfzo7vO6m/ExY5lh7xN1XfRCbxnYhfXh5r3G/kUuWlZEcc5vtR+olenfwrwtjSIBcfwEBTIBefqBvQVBMLNVhQLt9TiAMZ0k19wF9mQ4rpckvSKrclUMcxOY6/Afv6FJodtOHm//4mK4qv9GG8UcfxuubB3xsUMqrac2hOBdmWc2tHa0J9IN6HYURCKvEjbmXO2TQ27j/kg==
