#!/usr/bin/env python3
"""
Synchronise the RSA license public key into every place that needs it:

  1. ceva/src/data/LicenseManager.java     (PUBLIC_KEY_B64 constant)
  2. SERVERS/save_server/server_config.json     (license_public_key_b64)
  3. SERVERS/multiplayer_server/mp_config.json  (license_public_key_b64)

Reads the canonical key from build_tools/license_public.b64
(generated by generate_license_keys.py).

Idempotent: running it twice is a no-op.

Used by compile.cmd; can also be run manually after rotating the keypair.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

SCRIPT_DIR  = Path(__file__).resolve().parent
REPO_ROOT   = SCRIPT_DIR.parent
PUBKEY_FILE = SCRIPT_DIR / "license_public.b64"

LM_FILE          = REPO_ROOT / "ceva" / "src" / "data" / "LicenseManager.java"
SAVE_CONFIG_FILE = REPO_ROOT / "SERVERS" / "save_server"        / "server_config.json"
MP_CONFIG_FILE   = REPO_ROOT / "SERVERS" / "multiplayer_server" / "mp_config.json"

PLACEHOLDER = "REPLACE_WITH_PUBLIC_KEY_FROM_generate_license_keys.py"


def split_64(s: str) -> list[str]:
    return [s[i:i + 64] for i in range(0, len(s), 64)]


def inject_into_java(java_path: Path, pub_b64: str) -> bool:
    """
    Rewrite the multi-line PUBLIC_KEY_B64 = "..." + "..."; block in
    LicenseManager.java with the current key. Returns True if changed.
    """
    src = java_path.read_text(encoding="utf-8")
    pattern = re.compile(
        r'(private\s+static\s+final\s+String\s+PUBLIC_KEY_B64\s*=\s*)'
        r'(?:"[^"]*"\s*(?:\+\s*"[^"]*"\s*)*);',
        re.MULTILINE,
    )

    parts = split_64(pub_b64)
    new_literal = " + \n      ".join(f'"{p}"' for p in parts)
    new_block = f'\\g<1>{new_literal};'

    new_src, n = pattern.subn(new_block, src, count=1)
    if n == 0:
        # First-time installation case — try the placeholder swap.
        if PLACEHOLDER in src:
            new_src = src.replace(PLACEHOLDER, pub_b64)
            n = 1
        else:
            print(f"[WARN]  {java_path}: PUBLIC_KEY_B64 not found", file=sys.stderr)
            return False

    if new_src == src:
        print(f"[skip]  {java_path}: already up to date")
        return False

    java_path.write_text(new_src, encoding="utf-8")
    print(f"[OK]    {java_path}: public key injected")
    return True


def inject_into_json(json_path: Path, pub_b64: str) -> bool:
    if not json_path.exists():
        print(f"[WARN]  {json_path}: not found, skipping")
        return False
    cfg = json.loads(json_path.read_text(encoding="utf-8"))
    if cfg.get("license_public_key_b64") == pub_b64:
        print(f"[skip]  {json_path}: already up to date")
        return False
    cfg["license_public_key_b64"] = pub_b64
    # Preserve key order: write back with 2-space indent
    json_path.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    print(f"[OK]    {json_path}: public key updated")
    return True


def main() -> int:
    if not PUBKEY_FILE.exists():
        print(f"[ERROR] {PUBKEY_FILE} not found.", file=sys.stderr)
        print("        Run: python build_tools/generate_license_keys.py", file=sys.stderr)
        return 1

    pub_b64 = PUBKEY_FILE.read_text(encoding="utf-8").strip()
    if not pub_b64:
        print(f"[ERROR] {PUBKEY_FILE} is empty.", file=sys.stderr)
        return 1

    inject_into_java(LM_FILE,          pub_b64)
    inject_into_json(SAVE_CONFIG_FILE, pub_b64)
    inject_into_json(MP_CONFIG_FILE,   pub_b64)
    print("[done] Key sync complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
