package main;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class Main {

    public static JFrame window;
    public static final boolean OFFLINE_MODE = false;
    public static String LICENSE_KEY = null;  // Generated by installer → license.properties

    public static void main(String[] args) {

        // Load license from properties file (written by installer)
        try (java.io.InputStream in = new java.io.FileInputStream("license.properties")) {
            java.util.Properties props = new java.util.Properties();
            props.load(in);
            String key = props.getProperty("license_key");
            if (key != null && !key.isBlank()) LICENSE_KEY = key.trim();
        } catch (Exception ignored) { /* no license — cloud saves will be unavailable */ }

        // Enable OpenGL Java2D pipeline for smoother rendering.
        // V-Sync on/off is controlled from in-game settings.
        System.setProperty("sun.java2d.opengl", "True");
        // Force immediate hardware acceleration (skip default warmup)
        System.setProperty("sun.java2d.accthreshold", "0");

        window = new JFrame();
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setResizable(true);
        window.setTitle("Michi's Adventure " + Config.getVersionString());
        new Main().setIcon();

        GamePanel gamePanel = new GamePanel();
        window.add(gamePanel);

        gamePanel.config.loadConfig();

        window.pack();

        window.setLocationRelativeTo(null);
        window.setVisible(true);

        gamePanel.setupGame();
        gamePanel.startGameThread();

    }
    public void setIcon() {
        java.net.URL iconUrl = Main.class.getResource("/res/icon.png");
        if (iconUrl != null) {
            ImageIcon icon = new ImageIcon(iconUrl);
            window.setIconImage(icon.getImage());
        } else {
            System.out.println("Warning: icon not found at /res/icon.png");
        }
    }
}
