package main;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class Main {

    public static JFrame window;
    public static final boolean OFFLINE_MODE = false;
    public static final boolean DEBUG_MODE = true;
    public static volatile String LICENSE_KEY = null;  // Generated by installer → license.properties

    /**
     * Called by LicenseManager's watchdog the moment it detects on-disk
     * tampering, file swap, or machine-fingerprint drift. Nulling this
     * key forces all subsequent cloud-save / multiplayer connect attempts
     * to abort cleanly.
     */
    public static void invalidateLicense() {
        LICENSE_KEY = null;
    }

    public static void main(String[] args) {

        // Mandatory update check — must run before any window/game setup so
        // that, if an update is needed, we exit cleanly before the JAR file
        // is locked by anything heavyweight. Returns false when an update
        // was downloaded and the Updater has been spawned (or the user
        // declined a required update); in either case we must exit so the
        // running JAR can be replaced.
        if (!update.UpdateClient.checkAndApply()) {
            return;
        }

        // Load and verify the signed, machine-bound license.
        // LicenseManager checks the RSA signature and machine fingerprint.
        // Returns null silently on any failure — the game always runs.
        LICENSE_KEY = data.LicenseManager.load();

        // Start the local-verify watchdog: periodically re-validates the
        // signed license file against its cached state. If the file is
        // swapped, edited, or its machine fingerprint drifts mid-session,
        // it nulls LICENSE_KEY so cloud-save / multiplayer abort cleanly.
        if (LICENSE_KEY != null) {
            data.LicenseManager.startWatchdog(60);
        }

        // NOTE: sun.java2d.opengl is deliberately NOT enabled. The Java2D OpenGL
        // pipeline destroys/recreates its surface on every window-geometry change,
        // which produced a permanent black screen whenever the user toggled
        // fullscreen at runtime. Software rendering of a 1280x720 BufferedImage
        // back-buffer is plenty fast for this game and avoids the surface-loss bug.
        System.setProperty("sun.java2d.accthreshold", "0");
        System.setProperty("sun.java2d.translaccel", "true");
        System.setProperty("sun.java2d.renderer.useSimpleStroke", "true");

        // Dev mode: let ResourceCache read .tmx/.tsx files directly from src/res
        // so in-game R reload picks up Tiled edits without a resource sync step.
        if (DEBUG_MODE) {
            util.ResourceCache.setDevSourcePath(System.getProperty("user.dir") + "/ceva/src");
        }

        window = new JFrame();
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Always undecorated: avoids dispose()+setVisible() cycles when toggling fullscreen,
        // which destroy the OpenGL rendering surface and cause a blank window on many systems.
        window.setUndecorated(true);
        window.setResizable(true);
        window.setTitle("Michi's Adventure " + Config.getVersionString());
        new Main().setIcon();

        GamePanel gamePanel = new GamePanel();
        window.add(gamePanel);

        gamePanel.config.loadConfig();
        gamePanel.applyFpsTarget(gamePanel.config.fpsTarget);

        window.pack();

        if (gamePanel.fullScreenOn) {
            // Pre-size the window to the full screen BEFORE setVisible so the panel
            // is laid out at the right resolution on the very first paint. With the
            // OpenGL pipeline disabled (see top of main), plain setBounds is safe.
            java.awt.Rectangle sb = window.getGraphicsConfiguration().getBounds();
            window.setBounds(sb.x, sb.y, sb.width, sb.height);
        } else {
            if (gamePanel.config.windowX >= 0 && gamePanel.config.windowY >= 0) {
                window.setLocation(gamePanel.config.windowX, gamePanel.config.windowY);
            } else {
                window.setLocationRelativeTo(null);
            }
        }

        window.setVisible(true);

        gamePanel.setupGame();
        gamePanel.startGameThread();

    }
    public void setIcon() {
        java.net.URL iconUrl = Main.class.getResource("/res/icon.png");
        if (iconUrl != null) {
            ImageIcon icon = new ImageIcon(iconUrl);
            window.setIconImage(icon.getImage());
        } else {
            System.out.println("Warning: icon not found at /res/icon.png");
        }
    }
}
