license_key=MICHI-AND1
machine_fp=a11d201d00000000
signature=A8IvJZncE/lSCDxNn3ISWmnp7xJhuiYz5vayaoSAevPXyGfhbD8aCKDZRisSPbPwBJxUcLZdfhzMDjemvxUZd16OkKyMONRHQF3b9o26ULhJHgVa/MtGYE3Yvqq5X76769aE4UAsRZqg5CPRRryhDmbMVAh7bcRtkYIbPAn9y52Ws4tJ2dVKR1Ehs4c2B2XjMf7G6bDTfsCWyed09hOgCZEPTqZUjoLgEvYfebQFqpcLeKvlejlMDXiRTC9IuJkcZ7X410P+kAmOwJcCAc92Cbub04W8DXa0TRRqrFHUDeoNIJ+3qqKvSAgRRYZFtO1JFBDQQXiEwT6okA3AHD/f4A==
